$schema: "https://moonrepo.dev/schemas/tasks.json"

inheritedBy:
  tags: ["astro-plugin"]
  order: 20

fileGroups:
  sources:
    - "src/**/*"
    - "src/**/*.astro"
  tests:
    - "src/**/*.spec.ts"
    - "tests/**/*"

tasks:
  check-types:
    command: "astro"
    args: ["check"]
    toolchains: ["javascript", "node"]
    inputs:
      - "@group(sources)"
      - "@group(tests)"
      - "tsconfig.json"
    outputs: []
    options:
      mergeArgs: replace

  test:
    command: "vitest"
    args: ["run"]
    toolchains: ["javascript", "node"]
    inputs:
      - "@group(sources)"
      - "@group(tests)"
      - "vitest.config.ts"
    options:
      runInCI: true
      mergeArgs: replace

  test-watch:
    command: "vitest"
    args: ["run", "--watch"]
    toolchains: ["javascript", "node"]
    env:
      TDD: "1"
    inputs:
      - "@group(sources)"
      - "@group(tests)"
      - "vitest.config.ts"
    options:
      runInCI: false
