$schema: "https://moonrepo.dev/schemas/tasks.json"

fileGroups:
  cargo:
    - "Cargo.toml"
    - "src/**/*"
  sources: []
  tests:
    - "benches/**/*"
    - "tests/**/*"

tasks:


  cargo:
    command: "cargo"
    env: &env
      CARGO_TERM_COLOR: "always"
    options:
      runInCI: false

  debug-env:
    script: printenv | grep -E '^(CARGO|MOON|PROTOC|PROTO|PATH)'
    env: *env

  build: &build
    command: "cargo build"
    inputs:
      - "@group(cargo)"
      - "@group(sources)"
    env: *env

  build-release:
    <<: *build
    command: "cargo build --release"
    env: *env
    options:
      runInCI: false

  check:
    command: "cargo check --all-targets"
    inputs:
      - "@group(cargo)"
      - "@group(sources)"
      - "@group(tests)"
    env: *env

  dev:
    command: "cargo run"
    inputs:
      - "@group(cargo)"
      - "@group(sources)"
    preset: "server"
    env: *env

  lint:
    command: "cargo clippy --all-targets"
    inputs:
      - "@group(cargo)"
      - "@group(sources)"
      - "@group(tests)"
      - "/.clippy.toml"
    env: *env

  lint-fix:
    extends: "lint"
    args: "--fix --allow-dirty --allow-staged"
    options:
      runInCI: false

  test:
    command: "cargo nextest run --no-fail-fast -p $project"
    inputs:
      - "@group(cargo)"
      - "@group(sources)"
      - "@group(tests)"
      - "/.config/nextest.*"
      - "fuzz/regressions/**/*"
    env: *env

  fmt-check:
    command: "cargo fmt --check"
    inputs:
      - "@group(cargo)"
      - "@group(sources)"
    env: *env

  audit:
    command: "cargo"
    args: ["deny", "check"]
    inputs:
      - "@group(cargo)"
    env: *env


