# config/moon/.moon/toolchains.tera.yml
$schema: "https://moonrepo.dev/schemas/toolchain.json"
extends:
{% for t in moon.toolchains %}  - "toolchains-{{ t }}.yml"
{% endfor %}

proto:
  version: "0.55.4"
