$schema: "https://moonrepo.dev/schemas/workspace.json"

projects:
  globs:
    - "packages/*"
    - "apps/*"
    - "website"
  sources:
    root: "."

generator:
  templates:
    - ".moon/templates"

vcs:
  provider: "github"
  defaultBranch: "main"
  sync: true
  hooks:
    pre-commit:
      - "moon run :lint-ox-fix --affected --status=staged"
      - "moon run :fmt --affected --status=staged -- --incremental=false --allow-no-files"
      - "git diff --cached --name-only --diff-filter=ACMR | xargs git add -f"
    pre-push:
      - >
          branch="$(git branch --show-current)"; moon_cmd=(moon run :lint :fmt-check :test);

          git diff --quiet && git diff --cached --quiet || {
            echo "Dirty working tree. Commit all changes before pushing.";
            exit 1;
          };

          if [[ "$branch" != "main" ]]; then
            moon_cmd+=(--affected --base origin/main --head HEAD);
          else
            if ! .moon/scripts/auto-squash.sh check; then
              echo "Auto-squash aborted. Aborting git push.";
              exit 1;
            fi;
          fi;

          "${moon_cmd[@]}"

hasher:
  optimization: "accuracy"
