# Usage:
#   - uses: ./.github/actions/moon-ci
#     with:
#       access-token: ${{ secrets.GITHUB_TOKEN }}

name: "Moon CI"
description: "Run moon ci with sharding, reporting, and retrospect"

inputs:
  access-token:
    required: true
    description: "GITHUB_TOKEN for run report"

runs:
  using: composite
  steps:
    - name: Moon CI
      shell: bash
      run: |
        echo "Runner ${{ strategy.job-index }} of ${{ strategy.job-total }}"
        moon ci --color --job ${{ strategy.job-index }} --job-total ${{ strategy.job-total }}

    - uses: moonrepo/run-report-action@v1
      if: success() || failure()
      with:
        access-token: ${{ inputs.access-token }}
        matrix: '{"index": ${{ strategy.job-index }}, "total": ${{ strategy.job-total }}}'

    - uses: appthrust/moon-ci-retrospect@v1
      if: success() || failure()
